=== EdwardWangzhenwei/scgrbg/scgrbg/build/classes/db/sql_definition.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT sqls (sql+)>
<!ELEMENT sql ((i|o)+)>
<!ELEMENT i (#PCDATA)>
<!ELEMENT o (select,from+,join*,where?,group*,order*,having?)>
<!ELEMENT select (#PCDATA)>
<!ELEMENT from (def*)>
<!ELEMENT join EMPTY>
<!ELEMENT where (#PCDATA)>
<!ELEMENT group EMPTY>
<!ELEMENT order EMPTY>
<!ELEMENT having (#PCDATA)>
<!ELEMENT def (#PCDATA)>
<!ATTLIST sql	
	group CDATA #REQUIRED
	desp CDATA #IMPLIED
>
<!ATTLIST i
	id CDATA #REQUIRED	
	desp CDATA #IMPLIED
>
<!ATTLIST o
	id CDATA #REQUIRED	
	desp CDATA #IMPLIED
>
<!ATTLIST select>
<!ATTLIST from
	t CDATA #REQUIRED	
	f CDATA #IMPLIED
	as  CDATA #IMPLIED
	sub (true | false) "false"
>
<!ATTLIST join
	t CDATA #REQUIRED	
	f CDATA #REQUIRED	
	ot CDATA #REQUIRED	
	of CDATA #REQUIRED	
	type (left | right | none) "none"
>
<!ATTLIST where>
<!ATTLIST group
	t CDATA #REQUIRED	
	f CDATA #REQUIRED	
	exp CDATA #IMPLIED
>
<!ATTLIST order
	t CDATA #REQUIRED	
	f CDATA #REQUIRED	
	exp CDATA #IMPLIED
>
<!ATTLIST having>
<!ATTLIST def
	as CDATA #REQUIRED
>

=== EdwardWangzhenwei/scgrbg/scgrbg/build/classes/db/node_sql.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sqls SYSTEM "sql_definition.dtd">
<sqls>
	<sql group="node">
		<i id="fenfaupdate">
			update GZL_NODE set N_FACT_EXECUTOR =? ,N_STATUS = 2
			,N_FINISH_DATE = sysdate where fi_objectid =? and n_status = 0 and n_executor=?
		</i>
		<i id="shouhuiupdate">
			update gzl_node set n_status =3,n_finish_date=sysdate where  n_id = ?
		</i>
		<i id="fenfaqzshnode">
			update GZL_NODE set N_STATUS = 2 where N_ID !=? and
			FI_OBJECTID = ? and n_status = 0
		</i>
		<!-- 查询待办 -->
		<i id="queryDaiBan">
		<![CDATA[
	     SELECT f.bt,
         f.jjcd,
         F.ZH,
         F.NH,
         f.xh,
         f.hz,
         f.wjbm,
         F.WHXSGZ,
         c.n_id,
         c.n_uperid,
         c.n_status,
         c.fi_id,
         c.n_executor,
         c.n_fact_executor,
         c.n_fr_id,
         c.n_fr_name,
         c.n_sender,
         c.n_send_unit,
         to_char(c.n_send_date,'yyyy-mm-dd HH24:mi:ss') as n_send_date, 
         c.N_DBYXJ,
         c.n_ydbz,
         f.wjlx,
         c.N_LYS,
         f.llr_id
         FROM gw_fzxx f,gw_wjxs w,
         (SELECT *
            FROM gzl_node n
           WHERE 1 = 1 AND n_status = 0 AND n.n_executor = {user_id}) c
          WHERE     f.wjbm = c.fi_objectid and f.wjxs_id=w.wjxs_id
          AND (mj <= {user_secret} or mj is null)
          AND (f.zt != '-1' OR f.zt IS NULL)
          #querysql
          ORDER BY N_DBYXJ ASC, n_send_date DESC
          ]]>
		</i>
			<!-- 查询待办 -->
		<i id="queryYiBan">
		<![CDATA[
	    select d.* from (select wjbm,max(n_id) as n_id from( SELECT  
         c.n_id,f.wjbm
         FROM gw_fzxx f,
         (SELECT *
            FROM gzl_node n
           WHERE 1 = 1 AND ( n_status =2 or n_status=9) AND n.n_executor = #user_id) c
          WHERE     f.wjbm = c.fi_objectid
          AND (mj <= '#user_secret' or mj is null)
          AND (f.zt != '-1' OR f.zt IS NULL) and f.isygd!=1
          ORDER BY  n_send_date DESC ) a group by wjbm) b,( SELECT  f.bt,
         f.jjcd,
         f.wjbm,
         F.ZH,
         F.NH,
         f.xh,
         f.hz,
         F.WHXSGZ,
          f.lrbm,
          f.lrbm_id,
         f.llr,
         f.isygd,
         c.n_id,
         c.n_uperid,
         c.n_status,
         c.fi_id,
         c.n_executor,
         c.n_fact_executor,
         c.n_fr_id,
         c.n_fr_name,
         c.n_sender,
         c.n_send_unit,
         to_char(c.n_send_date,'yyyy-mm-dd HH24:mi:ss') as n_send_date, 
         c.N_DBYXJ,
         c.n_ydbz,
         f.wjlx,
         w.boc_id,
         c.N_LYS
         FROM gw_fzxx f,gw_wjxs w,
         (SELECT *
            FROM gzl_node n
           WHERE 1 = 1 AND ( n_status =2 or n_status=9) AND n.n_executor = #user_id) c
          WHERE     f.wjbm = c.fi_objectid and f.wjxs_id=w.wjxs_id 
          AND (mj <= '#user_secret' or mj is null)
          AND (f.zt != '-1' OR f.zt IS NULL)
          ORDER BY  n_send_date DESC ) d  where  d.n_id = b.n_id   #querysql 
          order by d.n_send_date desc
          ]]>
		</i>
	</sql>
	<sql group="shouhui">
		<i id="updateLDPS">
		   update gw_ldps set gzlid=? where gzlid = ?
		</i>
		<i id="updateGWJH">
			<![CDATA[
		     update gw_gwjh set zt='5' where wjbm = ? and  zt<>'2' and zt<>'3'  
		     ]]>
		</i>
		<i id="updateSW">
			<![CDATA[
		        update  gw_fzxx set bt='已被收回_'||bt  where wjbm=?
		     ]]>
		</i>
	</sql>
	<!--  <sql group="flowrole">
		<i id="queryFlowRole">
			SELECT a.fr_name as code, a.fr_name as name
			FROM gzl_flowrole a, GZL_BUSINESS_OBJECT_CLASS b
			WHERE b.boc_name like ?
			AND b.boc_id = a.boc_id
			AND a.SSDWID = b.ssdwid
			AND b.ssdwid = ?
			ORDER BY a.fr_order
		</i>
	</sql>-->
	<sql group="flowrole">
		<i id="queryFlowRole">
			SELECT
			    DISTINCT a . boc_id ,b.boc_id as code,b.boc_name as name
			FROM 
			    gw_wjxs a ,
			    gzl_business_object_class b 
			WHERE 
			    a . wjlx = ? 
			    AND a . ssdwid = ?
			    AND a . boc_id = b . boc_id 
			ORDER BY 
			    a . boc_id
		</i>
		<i id="queryFlowRole1">
			SELECT
				c.fr_name as code , c.fr_name as name
			FROM 
			    gzl_business_object_class b,
			    gzl_flowrole c
			WHERE 
				b.boc_id=?
				and  b.ssdwid=?
			    ANd b.ssdwid=c.ssdwid
			    AND b.boc_id=c.boc_id
			ORDER BY  c.fr_name

		</i>		
	</sql>
</sqls>

=== EdwardWangzhenwei/scgrbg/scgrbg/huadi/resource/db/login_sql.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sqls SYSTEM "sql_definition.dtd">
<sqls>
	<sql group="login">
		<i id="queryuser">
			select a.*,b.unit_name,b.unit_id ,b.unit_flag,d.user_level as user_level_name from priv_user
			a,priv_unit
			b,priv_unit_user c,priv_user_level d where a.user_account_name = ? and
			a.user_id
			=c.user_id
			and b.unit_id= c.unit_id and a.abate=1 and
			b.abate=1 and d.user_level_id=a.user_level and c.type='0'
		</i>
	</sql>
	<sql group="login">
		<i id="queryunit">
			select unit_id,unit_name,unit_flag,credit_code,subunit_code from (select * from priv_unit b start
			with unit_id
			=? connect by prior uper_unit_id=unit_id ) c where
			c.abate =1 order by unit_coding desc
		</i>
	</sql>
	<sql group="privsys">
		<i id="queryUserTopFunctions">
			select distinct c.* from priv_function c, priv_subsystem e,(select distinct
			b.function_id
			from priv_user_role a,priv_role_function b where a.user_id=? and
			a.role_id = b.role_id) d where
			c.function_id = d.function_id and c.abate =1 and c.uper_function_id =0 and
			e.subsystem_code =? and
			e.subsystem_id=c.subsystem_id  order by c.function_sort
		</i>
	</sql>
	<sql group="privsys">
		<i id="queryUserFunctions_bk">
			SELECT vv.*,
			(SELECT COUNT (1)
			FROM (SELECT function_name,
			uper_function_id, function_discription,
			function_id
			FROM (SELECT
			DISTINCT f.function_id, f.uper_function_id,
			f.function_name,
			f.function_discription
			FROM priv_function f,
			priv_role r,
			priv_role_function rf,
			priv_user_role ur
			WHERE f.function_id =
			rf.function_id
			AND rf.role_id = r.role_id
			AND
			ur.user_id = ?
			and f.abate =1
			ORDER BY f.function_id)) pp
			WHERE
			pp.uper_function_id = vv.function_id) AS
			cn
			FROM (SELECT
			function_name, uper_function_id, function_discription,
			function_id,level,function_sort
			FROM (SELECT DISTINCT f.function_id,
			f.uper_function_id,
			f.function_name, f.function_discription,f.function_sort
			FROM
			priv_function f,
			priv_role r,
			priv_role_function rf,
			priv_user_role ur
			WHERE
			f.function_id = rf.function_id
			AND rf.role_id = r.role_id
			and ur.role_id = r.role_id
			AND ur.user_id =?
			and f.abate =1
			ORDER BY f.function_id) t
			START WITH
			t.uper_function_id = ?
			CONNECT BY PRIOR t.function_id =
			t.uper_function_id order SIBLINGS BY t.function_sort) vv
		</i>
		<i id="queryUserFunctions">
			<![CDATA[
				SELECT
				    vv . * ,
				    (
				    SELECT
				        count (1 )
				    FROM 
				        (
				        SELECT
				            function_name ,
				            uper_function_id ,
				            function_discription ,
				            function_id 
				        FROM 
				            (
				            SELECT
				                DISTINCT f . function_id ,
				                f . uper_function_id ,
				                f . function_name ,
				                f . function_discription,
				                f.function_sort 
				            FROM 
				                priv_function f ,
				                priv_role r ,
				                priv_role_function rf ,
				                priv_user_role ur,
				                priv_subsystem s 
				            WHERE 
				                f . function_id = rf . function_id 
				                AND rf . role_id = r . role_id
				                and r.role_id=ur.role_id 
				                AND ur . user_id = ? 
				                and s.subsystem_id=f.subsystem_id
				                AND s . subsystem_code = ?
				            ORDER BY 
				                f.function_sort,f . function_id 
				            ) 
				            ) pp 
				        WHERE 
				            pp . uper_function_id = vv . function_id ) AS cn 
				    FROM 
				        (
				        SELECT
				            function_name ,
				            uper_function_id ,
				            function_discription ,
				            function_id ,
				            function_sort,
				            LEVEL 
				        FROM 
				            (
				            SELECT
				                DISTINCT f . function_id ,
				                f . uper_function_id ,
				                f . function_name ,
				                f . function_discription,
				                f.function_sort 
				            FROM 
				                priv_function f ,
				                priv_role r ,
				                priv_role_function rf ,
				                priv_user_role ur,
				                priv_subsystem s 
				            WHERE 
				                f . function_id = rf . function_id 
				                AND rf . role_id = r . role_id 
				                and r.role_id=ur.role_id
				                AND ur . user_id = ? 
				                and s.subsystem_id=f.subsystem_id
				                AND s . subsystem_code = ?
				            ORDER BY 
				                f.function_sort,f . function_id 
				            ) t START WITH t . uper_function_id = '0' CONNECT 
				        BY 
				            PRIOR t . function_id = t . uper_function_id 
				            ) vv order by vv.level ,vv.function_sort
			]]>
		</i>
	</sql>
</sqls>

=== EdwardWangzhenwei/scgrbg/scgrbg/huadi/resource/db/fw_sql.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sqls SYSTEM "sql_definition.dtd">
<sqls>
	<sql group="fw">
		<i id="getFaWenById">
			SELECT
			FW.WJBM,FW.ZXFW,FW.MDMS,TO_CHAR(FW.XBRQ,'YYYY-MM-DD
			HH24:MI:SS') AS
			XBRQ,FW.GKXS,FW.GKYY,FW.FWFS,FW.DZGWFS,FW.ZZGWFS,FW.ZS,
			FW.CS,FW.QFR,TO_CHAR(FW.QFRQ,'YYYY-MM-DD HH24:MI:SS') AS
			QFRQ,TO_CHAR(FW.YFRQ,'YYYY-MM-DD HH24:MI:SS') AS
			YFRQ,FW.FBCC,FW.NGR,TO_CHAR(FW.NGRQ,'YYYY-MM-DD HH24:MI:SS') AS
			NGRQ,FW.NGRDH,TO_CHAR(FW.CYSJ,'YYYY-MM-DD HH24:MI:SS') AS
			CYSJ,FW.NGDW,FW.CX,FW.QJ,FW.LX,FW.QFRZW,
			FW.YFJG,FW.FWJGSM,TO_CHAR(FW.CWRQ,'YYYY-MM-DD HH24:MI:SS') AS CWRQ,FW.FZ,FW.DW,
			FZXX.WJXS_ID,FZXX.SSDWID,FZXX.WJLX,FZXX.BT,FZXX.MJ,FZXX.BMQX,FZXX.QXLB,FZXX.JJCD,FZXX.ZH,FZXX.NH,
			FZXX.XH,FZXX.HZ,FZXX.WHXSGZ,FZXX.LLR,FZXX.LLR_ID,TO_CHAR(FZXX.LRSJ,'YYYY-MM-DD
			HH24:MI:SS') AS
			LRSJ,FZXX.LRBM,FZXX.LRBM_ID,FZXX.LRDW,FZXX.LRDW_ID,FZXX.NBYJ,
			FZXX.ZT,FZXX.ZTR,TO_CHAR(FZXX.ZTSJ,'YYYY-MM-DD HH24:MI:SS') AS
			ZTSJ,
			FZXX.LSH,FZXX.DZGWBS,FZXX.ISYGD,
			WJXS.WJXS,WJXS.WZ,
			N.N_ID,N.FI_ID,N.N_UPERID,N.N_SUBSYSID,N.FI_CLASS,N.FI_OBJECTID,N.N_FR_ID,N.N_FR_NAME,N.N_SEND_UNIT,
			N.N_SENDER,N.N_SENDER_ID,TO_CHAR(N.N_SEND_DATE,'YYYY-MM-DD
			HH24:MI:SS') AS N_SEND_DATE,N.N_EXECUTOR,
			N.N_EXECUTORNAME,N.N_FACT_EXECUTOR,N.N_STATUS,TO_CHAR(N.N_FINISH_DATE,'YYYY-MM-DD
			HH24:MI:SS')
			AS
			N_FINISH_DATE,N.N_LY,N.N_YDBZ,N.N_ISWORK,N.N_DBYXJ,TO_CHAR(N.N_YD_TIME,'YYYY-MM-DD
			HH24:MI:SS') AS N_YD_TIME,
			N.N_FFRECID,N.N_LYS,N.N_DB,N.N_ISZHONGDIAN,N.N_PX
			FROM
			gw_fw fw,gw_fzxx
			fzxx,gw_wjxs
			wjxs,gzl_node n
			WHERE
			fw.wjbm = fzxx.wjbm
			and
			wjxs.wjxs_id=fzxx.wjxs_id
			and n.fi_objectid=fw.wjbm
			AND
			fw.wjbm=? and
			n.n_id=?
		</i>
		<i id="getFaWenById2">
			SELECT
			FW.WJBM,FW.ZXFW,FW.MDMS,TO_CHAR(FW.XBRQ,'YYYY-MM-DD
			HH24:MI:SS') AS
			XBRQ,FW.GKXS,FW.GKYY,FW.FWFS,FW.DZGWFS,FW.ZZGWFS,FW.ZS,
			FW.CS,FW.QFR,TO_CHAR(FW.QFRQ,'YYYY-MM-DD HH24:MI:SS') AS
			QFRQ,TO_CHAR(FW.YFRQ,'YYYY-MM-DD HH24:MI:SS') AS
			YFRQ,FW.FBCC,FW.NGR,TO_CHAR(FW.NGRQ,'YYYY-MM-DD HH24:MI:SS') AS
			NGRQ,FW.NGRDH,TO_CHAR(FW.CYSJ,'YYYY-MM-DD HH24:MI:SS') AS
			CYSJ,FW.NGDW,FW.CX,FW.QJ,FW.LX,FW.QFRZW,
			FW.YFJG,FW.FWJGSM,TO_CHAR(FW.CWRQ,'YYYY-MM-DD HH24:MI:SS') AS CWRQ,FW.FZ,FW.DW,
			FZXX.WJXS_ID,FZXX.SSDWID,FZXX.WJLX,FZXX.BT,FZXX.MJ,FZXX.BMQX,FZXX.QXLB,FZXX.JJCD,FZXX.ZH,FZXX.NH,
			FZXX.XH,FZXX.HZ,FZXX.WHXSGZ,FZXX.LLR,FZXX.LLR_ID,TO_CHAR(FZXX.LRSJ,'YYYY-MM-DD
			HH24:MI:SS') AS
			LRSJ,FZXX.LRBM,FZXX.LRBM_ID,FZXX.LRDW,FZXX.LRDW_ID,FZXX.NBYJ,
			FZXX.ZT,FZXX.ZTR,TO_CHAR(FZXX.ZTSJ,'YYYY-MM-DD HH24:MI:SS') AS
			ZTSJ,
			FZXX.LSH,FZXX.DZGWBS,FZXX.ISYGD,
			WJXS.WJXS,WJXS.WZ,
			N.N_ID,N.FI_ID,N.N_UPERID,N.N_SUBSYSID,N.FI_CLASS,N.FI_OBJECTID,N.N_FR_ID,N.N_FR_NAME,N.N_SEND_UNIT,
			N.N_SENDER,N.N_SENDER_ID,TO_CHAR(N.N_SEND_DATE,'YYYY-MM-DD
			HH24:MI:SS') AS N_SEND_DATE,N.N_EXECUTOR,
			N.N_EXECUTORNAME,N.N_FACT_EXECUTOR,N.N_STATUS,TO_CHAR(N.N_FINISH_DATE,'YYYY-MM-DD
			HH24:MI:SS')
			AS
			N_FINISH_DATE,N.N_LY,N.N_YDBZ,N.N_ISWORK,N.N_DBYXJ,TO_CHAR(N.N_YD_TIME,'YYYY-MM-DD
			HH24:MI:SS') AS N_YD_TIME,
			N.N_FFRECID,N.N_LYS,N.N_DB,N.N_ISZHONGDIAN,N.N_PX
			FROM
			gw_fw fw,gw_fzxx
			fzxx,gw_wjxs
			wjxs,gzl_node n
			WHERE
			fw.wjbm = fzxx.wjbm
			and
			wjxs.wjxs_id=fzxx.wjxs_id
			and n.fi_objectid=fw.wjbm
			and n.n_status=0 and n.n_executor=?
			AND
			fw.wjbm=? order by n.n_id desc
		</i>
		<i id="getFaWenById3">
			SELECT
			FW.WJBM,FW.ZXFW,FW.MDMS,TO_CHAR(FW.XBRQ,'YYYY-MM-DD
			HH24:MI:SS') AS
			XBRQ,FW.GKXS,FW.GKYY,FW.FWFS,FW.DZGWFS,FW.ZZGWFS,FW.ZS,
			FW.CS,FW.QFR,TO_CHAR(FW.QFRQ,'YYYY-MM-DD HH24:MI:SS') AS
			QFRQ,TO_CHAR(FW.YFRQ,'YYYY-MM-DD HH24:MI:SS') AS
			YFRQ,FW.FBCC,FW.NGR,TO_CHAR(FW.NGRQ,'YYYY-MM-DD HH24:MI:SS') AS
			NGRQ,FW.NGRDH,TO_CHAR(FW.CYSJ,'YYYY-MM-DD HH24:MI:SS') AS
			CYSJ,FW.NGDW,FW.CX,FW.QJ,FW.LX,FW.QFRZW,
			FW.YFJG,FW.FWJGSM,TO_CHAR(FW.CWRQ,'YYYY-MM-DD HH24:MI:SS') AS CWRQ,FW.FZ,FW.DW,
			FZXX.WJXS_ID,FZXX.SSDWID,FZXX.WJLX,FZXX.BT,FZXX.MJ,FZXX.BMQX,FZXX.QXLB,FZXX.JJCD,FZXX.ZH,FZXX.NH,
			FZXX.XH,FZXX.HZ,FZXX.WHXSGZ,FZXX.LLR,FZXX.LLR_ID,TO_CHAR(FZXX.LRSJ,'YYYY-MM-DD
			HH24:MI:SS') AS
			LRSJ,FZXX.LRBM,FZXX.LRBM_ID,FZXX.LRDW,FZXX.LRDW_ID,FZXX.NBYJ,
			FZXX.ZT,FZXX.ZTR,TO_CHAR(FZXX.ZTSJ,'YYYY-MM-DD HH24:MI:SS') AS
			ZTSJ,
			FZXX.LSH,FZXX.DZGWBS,FZXX.ISYGD,
			WJXS.WJXS,WJXS.WZ,
			N.N_ID,N.FI_ID,N.N_UPERID,N.N_SUBSYSID,N.FI_CLASS,N.FI_OBJECTID,N.N_FR_ID,N.N_FR_NAME,N.N_SEND_UNIT,
			N.N_SENDER,N.N_SENDER_ID,TO_CHAR(N.N_SEND_DATE,'YYYY-MM-DD
			HH24:MI:SS') AS N_SEND_DATE,N.N_EXECUTOR,
			N.N_EXECUTORNAME,N.N_FACT_EXECUTOR,N.N_STATUS,TO_CHAR(N.N_FINISH_DATE,'YYYY-MM-DD
			HH24:MI:SS')
			AS
			N_FINISH_DATE,N.N_LY,N.N_YDBZ,N.N_ISWORK,N.N_DBYXJ,TO_CHAR(N.N_YD_TIME,'YYYY-MM-DD
			HH24:MI:SS') AS N_YD_TIME,
			N.N_FFRECID,N.N_LYS,N.N_DB,N.N_ISZHONGDIAN,N.N_PX
			FROM
			gw_fw fw,gw_fzxx
			fzxx,gw_wjxs
			wjxs,gzl_node n
			WHERE
			fw.wjbm = fzxx.wjbm
			and
			wjxs.wjxs_id=fzxx.wjxs_id
			and n.fi_objectid=fw.wjbm
			and n.n_executor=?
			AND
			fw.wjbm=? order by n.n_id desc
		</i>
		<i id="queryFaWen"><![CDATA[
			SELECT DISTINCT FW.WJBM,FW.ZXFW,FW.MDMS,TO_CHAR(FW.XBRQ,'YYYY-MM-DD
			HH24:MI:SS') AS
			XBRQ,FW.GKXS,FW.GKYY,FW.FWFS,FW.DZGWFS,FW.ZZGWFS,FW.ZS,
			FW.CS,FW.QFR,TO_CHAR(FW.QFRQ,'YYYY-MM-DD HH24:MI:SS') AS
			QFRQ,TO_CHAR(FW.YFRQ,'YYYY-MM-DD HH24:MI:SS') AS
			YFRQ,FW.FBCC,FW.NGR,TO_CHAR(FW.NGRQ,'YYYY-MM-DD HH24:MI:SS') AS
			NGRQ,FW.NGRDH,TO_CHAR(FW.CYSJ,'YYYY-MM-DD HH24:MI:SS') AS
			CYSJ,FW.NGDW,FW.CX,FW.QJ,FW.LX,FW.QFRZW,
			FW.YFJG,FW.FWJGSM,TO_CHAR(FW.CWRQ,'YYYY-MM-DD HH24:MI:SS') AS CWRQ,FW.FZ,FW.DW,
			FZXX.WJXS_ID,FZXX.SSDWID,FZXX.WJLX,FZXX.BT,FZXX.MJ,FZXX.BMQX,FZXX.QXLB,FZXX.JJCD,FZXX.ZH,FZXX.NH,
			FZXX.XH,FZXX.HZ,FZXX.WHXSGZ,FZXX.LLR,FZXX.LLR_ID,TO_CHAR(FZXX.LRSJ,'YYYY-MM-DD
			HH24:MI:SS') AS
			LRSJ,FZXX.LRBM,FZXX.LRBM_ID,FZXX.LRDW,FZXX.LRDW_ID,FZXX.NBYJ,
			FZXX.ZT,FZXX.ZTR,TO_CHAR(FZXX.ZTSJ,'YYYY-MM-DD HH24:MI:SS') AS
			ZTSJ,
			FZXX.LSH,FZXX.DZGWBS,FZXX.ISYGD,
			WJXS.WJXS,WJXS.WZ 
			FROM GW_FZXX FZXX,GW_FW FW,GW_WJXS WJXS WHERE
			FW.WJBM=FZXX.WJBM AND 
			WJXS.WJLX='发文' AND 
			FZXX.WJXS_ID=WJXS.WJXS_ID AND (FZXX.ZT IS NULL
			or FZXX.ZT<>-1) 
		]]></i>
		<i id="getbangongById">
			SELECT * FROM GDZC_BGYPLF FW,GW_FZXX FZXX,GW_WJXS WJXS,GZL_NODE N WHERE
			FW.WJBM = FZXX.WJBM AND WJXS.WJXS_ID=FZXX.WJXS_ID AND
			N.FI_OBJECTID=FW.WJBM AND
			FW.WJBM=? AND
			N.N_ID=?  	
		</i>
		<i id="getJiaojieById">
			SELECT * FROM GDZC_ZCJJ FW,GW_FZXX FZXX,GW_WJXS WJXS,GZL_NODE N WHERE
			FW.WJBM = FZXX.WJBM AND WJXS.WJXS_ID=FZXX.WJXS_ID AND
			N.FI_OBJECTID=FW.WJBM AND
			FW.WJBM=? AND
			N.N_ID=?  	
		</i>
		<i id="getBaofeiById">
			SELECT * FROM GDZC_WSBF FW,GW_FZXX FZXX,GW_WJXS WJXS,GZL_NODE N WHERE
			FW.WJBM = FZXX.WJBM AND WJXS.WJXS_ID=FZXX.WJXS_ID AND
			N.FI_OBJECTID=FW.WJBM AND
			FW.WJBM=? AND
			N.N_ID=?  	
		</i>
	</sql>
</sqls>

=== EdwardWangzhenwei/scgrbg/scgrbg/build/classes/db/dictionary_sql.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sqls SYSTEM "sql_definition.dtd">
<sqls>
	<sql group="dictionary">
		<i id="getNewDictionaryId"><![CDATA[
			select nvl(max(DICT_ID)+1,1) from DICT_DICTIONARY where 1={}
		]]></i>
		<i id="getDictionaryInfoById"><![CDATA[
			select * from DICT_DICTIONARY where DICT_ID={}
		]]></i>
		<i id="getDictionaryInfoByUperId"><![CDATA[
			select * from DICT_DICTIONARY where UPER_DICT_ID={} and
			show_flag=1
		]]></i>
		<i id="getDictionaryInfoByCode"><![CDATA[
			SELECT
			    d . * 
			FROM 
			    dict_category AS c ,
			     dict_dictionary AS d ,
			     dict_group AS G 
			WHERE 
			    c . category_id = G . category_id 
			    AND G . group_code = d . group_code 
			    and d.show_flag=1
			    AND G . group_code = {} 
			    AND d . dict_code = {}
		]]></i>
		<i id="getDictionaryTreeByGroup"><![CDATA[
		 select 
				dict.dict_id code,
				decode(EFFECTIVE_FLAG,1,dict_name,concat(dict_name,'(无效)'))  name,
				dict.UPER_DICT_ID as fatherid, 
				dict.DICT_ORDER as orderby
			from 
				DICT_DICTIONARY dict
			where 
				 dict.group_code={} and show_flag=1
		]]></i>
		<i id="getUperIsLeafById"><![CDATA[
			select DICT_ID from DICT_DICTIONARY where UPER_DICT_ID=(
			select
			UPER_DICT_ID from DICT_DICTIONARY where DICT_ID={}) and
			show_flag=1
		]]></i>
		<!-- <i id="getDictionaryInfoByGroupCode"><![CDATA[ 
			select dict_code as 
			code,dict_name as name,dict_order from DICT_DICTIONARY where group_code ={} 
			and show_flag=1 order by dict_order 
			]]></i> -->


		<i id="getDictionaryInfoByGroupCode"><![CDATA[
			SELECT
			    d.dict_code as code,d.dict_name as name,d.dict_order 
			FROM 
			    dict_category AS c ,
			    dict_dictionary AS d ,
			    dict_group AS g 
			WHERE 
				c . category_id = g . category_id 
			    AND g . group_code = {} 
			    AND g . group_code = d . group_code
			    AND show_flag=1 
			    order by dict_order
		]]></i>
		<i id="getDictionaryByGroupCode"><![CDATA[
			select dict_code as code,dict_name as name from
			DICT_DICTIONARY where
			group_code ={} and show_flag=1
		]]></i>
		<i id="getDictionaryInfoByGroupName"><![CDATA[
			select dict.dict_code code,dict.dict_name name from
			DICT_DICTIONARY
			dict,dict_group groups where
			dict.group_code=groups.group_code and
			groups.group_name={} and
			dict.show_flag=1 order by dict.dict_code
		]]></i>
		<!-- <i id="getDictionaryByGroupNameAndSecret"> select dict.dict_code code,dict.dict_name 
			name from DICT_DICTIONARY dict,dict_group groups where dict.group_code=groups.group_code 
			and groups.group_name={} and dict.dict_code &lt;= {} order by dict.dict_code 
			</i> -->
		<i id="getDictionaryByGroupNameAndSecret"><![CDATA[
			SELECT
			    dict . dict_code code ,
			    dict . dict_name NAME 
			FROM 
			     dict_category AS c ,
			     dict_dictionary dict ,
			     dict_group groups 
			WHERE 
			    c . category_id = groups . category_id 
			    AND dict . show_flag = '1' 
			    AND dict . group_code = groups . group_code 
			    AND groups . group_code = {} 
			    AND dict . dict_code <= {} 
			ORDER BY 
			    dict . dict_code
		]]></i>
		<i id="getDictionaryNameByGroupName"><![CDATA[
			select
			dict.dict_name code,
			dict.dict_name name
			from
			DICT_DICTIONARY dict,
			dict_group groups,
			DICT_CATEGORY category
			where
			category.CATEGORY_NAME={}
			and category.CATEGORY_ID = groups.CATEGORY_ID
			and
			dict.group_code=groups.group_code
			and groups.group_name={}
			and dict.show_flag=1
			order by dict.dict_code
		]]></i>
	</sql>
</sqls>
